Add the mailto: example
TeamDev-IP/JxBrowser-Examples pull request #58
Opened 2020-10-08 10:53 UTC by ivan-diachenko-td

Now there is no possibility to open a desktop mail app by clicking `mailto:` link in JxBrowser. This PR suggests the workaround on how to open a default mail client in the environment using `Desktop` class.

2020-10-08 11:02 UTC, ivan-diachenko-td commented
@vladimir-ikryanov @vlad-lubenskyi PTAL

2020-10-08 11:02 UTC, vladimir-ikryanov requested changes

2020-10-08 11:02 UTC, vladimir-ikryanov commented on network/src/main/java/MailTo.java
> + * This example demonstrates how to open a default desktop mail client by clicking {@code mailto:} links.
The idea of this example is not to show how to open a default desktop mail client. It should explain how to handle the case when user clicks a link with the "mailto:" URL and expects that a default desktop mail client is opened with the target email address, so they can send an email.

2020-10-08 13:25 UTC, ivan-diachenko-td commented on network/src/main/java/MailTo.java
> +                    throw new RuntimeException(e);
Changed to `printStackTrace`

2020-10-08 13:26 UTC, ivan-diachenko-td commented
@vladimir-ikryanov PTAL

2020-10-09 08:07 UTC, vladimir-ikryanov approved these changes
LGTM

2020-10-09 08:37 UTC, anna-dolbina commented on network/src/main/java/HandleMailToClick.java
> +                if (isDesktopSupported() && desktop.isSupported(Desktop.Action.MAIL)) {
Consider checking `isDesktopSupported` before calling `Desktop.getDesktop()`. In other case, you may get an `UnsupportedOperationException`:
https://docs.oracle.com/javase/9/docs/api/java/awt/Desktop.html#getDesktop--

2020-10-09 15:50 UTC, merged