Add guava dependency to the "input" project
TeamDev-IP/JxBrowser-Examples pull request #61
Opened 2020-11-02 14:09 UTC by serhii-kozionov

Fixes an issue with a missing guava dependency after #59. 
Also bumps the guava version to `29.0`.

2020-11-02 14:10 UTC, serhii-kozionov commented
@vladimir-ikryanov Maybe add guava to the whole `JxBrowser-Examples` project? For now, only 2 submodules uses it.

2020-11-02 15:14 UTC, vladimir-ikryanov requested changes

2020-11-02 15:14 UTC, vladimir-ikryanov commented on input/build.gradle
> +    // Depend on Guava for the Uninterruptibles utility class to wait for the latch.
I don't think we need to explain why we add some dependency.

2020-11-02 18:18 UTC, serhii-kozionov commented
@vladimir-ikryanov PTAL

2020-11-03 07:54 UTC, vladimir-ikryanov approved these changes
LGTM

2020-11-03 08:20 UTC, merged