Add example programs for adding DOM events listeners
TeamDev-IP/JxBrowser-Examples pull request #62
Opened 2020-11-11 09:30 UTC by vlad-lubenskyi

In this pull request, we introduce two example programs demonstrating how to listen to the keyboard and mouse DOM events.

2020-11-11 16:33 UTC, vladimir-ikryanov requested changes

2020-11-11 16:33 UTC, vladimir-ikryanov commented on dom/src/main/java/KeyboardEventListener.java
> +                    element.addEventListener(EventType.KEY_DOWN, KeyboardEventListener::printEventDetails, false);
Reformat. I suppose the line length is more than 80-100 characters.

2020-11-11 16:33 UTC, vladimir-ikryanov commented on dom/src/main/java/KeyboardEventListener.java
> +        EngineOptions options = EngineOptions.newBuilder(HARDWARE_ACCELERATED)
We usually use more compact way:
```java
Engine engine = Engine.newInstance(
        EngineOptions.newBuilder(HARDWARE_ACCELERATED)
                .build());
```

2020-11-11 16:33 UTC, vladimir-ikryanov commented on dom/src/main/java/MouseEventListener.java
> +        EngineOptions options = EngineOptions.newBuilder(HARDWARE_ACCELERATED)
Same suggestion here.

2020-11-11 16:33 UTC, vladimir-ikryanov commented on dom/src/main/java/MouseEventListener.java
> +                    element.addEventListener(EventType.MOUSE_DOWN, MouseEventListener::printEventDetails, false);
Same issue with line length.

2020-11-11 16:33 UTC, vladimir-ikryanov commented on dom/src/main/java/MouseEventListener.java
> +            JFrame frame = new JFrame("DOM Mouse Event Listener ");
Extra space in the title.

2020-11-12 10:02 UTC, vlad-lubenskyi commented on dom/src/main/java/KeyboardEventListener.java
> +        EngineOptions options = EngineOptions.newBuilder(HARDWARE_ACCELERATED)
I find it uglier :)

2020-11-12 10:08 UTC, vladimir-ikryanov approved these changes
LGTM

2020-11-12 11:38 UTC, merged